format = """
[](fg:bar_one)\
$username\
[](fg:bar_one bg:bar_three)\
$directory\
[](fg:bar_three bg:bar_four)\
$git_branch\
$git_status\
[ ](fg:bar_four)\
$fill\
[ ](fg:bar_four)\
$cmd_duration\
[](fg:bar_three bg:bar_four)\
$status\
[](fg:bar_one bg:bar_three)\
$os$hostname\
[](fg:bar_one)\
\n [╰─ $character](fg:bar_one)
"""

palette = 'theme'

# Defines the colour palette for the theme
[palettes.theme]
bar_one = '#FDA172'
bar_two = '#ED7014'
bar_three = '#BE5504'
bar_four = '#8D4004'
bar_five = '#1D2230'
text_one = '#090C0C'
text_two = '#EEEEEE'
text_three = '#A3AED2'

[fill]
symbol = ' '
style = 'bar_one'

[cmd_duration]
min_time = 0
format = '[ $duration ](fg:text_three bg:bar_four)'

[username]
format = '[ $user](fg:text_one bg:bar_one)'
disabled = false
show_always = true

[aws]
format = '[󰅟 ($profile )(\($region\))](fg:text_one bg:bar_one)'
[aws.region_aliases]
us-west-1 = 'CA'
us-west-2 = 'OR'
us-east-1 = 'OH'
us-east-2 = 'VA'
eu-west-1 = 'IR'
[aws.profile_aliases]
default = 'Sushamae'
PortfolioWebsite = 'Portfolio'

[hostname]
style = 'bg:bar_one fg:text_one'
ssh_symbol = ' '
ssh_only = false
format = '[ $hostname$ssh_symbol]($style)'
trim_at = '.companyname.com'
disabled = false

[os]
style = 'bg:bar_one fg:text_one'
format = '[$symbol]($style)'
disabled = false

[os.symbols]
CentOS = ''
Debian = ''
Fedora = ''
Linux = ""
Macos = "󰀵"
NixOS = ''
Raspbian = ''
Ubuntu = ''
Windows = ''

[status]
style = 'fg:text_two bg:bar_three'
symbol = ' Error '
success_symbol = ' Success '
not_executable_symbol = ' NonExec '
not_found_symbol = ' NotFound '
sigint_symbol = '󱊈 SigInt '
signal_symbol = '󱐋 Signal '
format = '[$symbol$maybe_int]($style)'
map_symbol = true
disabled = false

[directory]
read_only = " 󰏮"
truncation_length = 1
truncation_symbol = '…/'
truncate_to_repo = false
fish_style_pwd_dir_length = 1
style = 'bold fg:text_two bg:bar_three'
format = '[  $path$read_only]($style)'

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ''
'Music' = ''
'Pictures' = ''

[git_branch]
symbol = ""
style = "fg:text_three bg:bar_four"
format = '[ $symbol $branch]($style)'

[git_status]
style = "fg:text_three bg:bar_four"
format = '[ $all_status$ahead_behind]($style)'
