theme = "ayu_mirage"

[editor]
line-number = "relative"
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false

[keys.normal]
C-o = ":open ~/.config/helix/config.toml" # Maps Ctrl-o to opening of the helix config file
C-r = ":config-reload"

# Use system clipboard
p = "paste_clipboard_before"
y = "yank_main_selection_to_clipboard"

[keys.normal.space.","]
e = ":sh $HOME/.config/helix/helix-tmux.sh explorer"
t = ":sh $HOME/.config/helix/helix-tmux.sh terminal"
g = ":sh $HOME/.config/helix/helix-tmux.sh tgpt"

